const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ts=require('../frontend/node_modules/typescript');
function load(path,customRequire=require){const context={exports:{},require:customRequire};vm.createContext(context);vm.runInContext(ts.transpile(fs.readFileSync(path,'utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}),context);return context.exports;}
const timing=load('frontend/src/lib/karaoke-timing.ts');
const lib=load('frontend/src/lib/audio-passages.ts',()=>timing);
const joined={start:113.911,end:115.251,text:'FİKRİMDEN CAYABİLİRİM.',words:[
  {word:'FİKRİMDEN',start:113.911,end:114.711,timing_source:'manual'},
  {word:'CAYABİLİRİM.',start:114.711,end:115.251,timing_source:'manual',needs_review:true}]};
const joinedDraft={segment:joined,passages:lib.passagePool(joined)};
const beforeSplit=JSON.stringify(joinedDraft);
const splitBound=lib.splitAndBindPassage(joinedDraft,joinedDraft.passages[1].id,114.86,1,'bile','cayabilirim.');
assert.equal(splitBound.segment.text,'FİKRİMDEN BİLE CAYABİLİRİM.');
assert.equal(splitBound.segment.words[0].start,113.911);assert.equal(splitBound.segment.words[0].end,114.711);
assert.equal(splitBound.segment.words[1].start,114.711);assert.equal(splitBound.segment.words[1].end,114.86);
assert.equal(splitBound.segment.words[2].start,114.86);assert.equal(splitBound.segment.words[2].end,115.251);
assert.equal(splitBound.segment.words[1].needs_review,true);
assert.equal(splitBound.passages.length,3);assert.equal(new Set(splitBound.passages.map(p=>p.id)).size,3);
assert.equal(timing.timingIssues([splitBound.segment],false).length,0);
assert.equal(JSON.stringify(joinedDraft),beforeSplit);
for(const at of [114.711,115.251,NaN])assert.throws(()=>lib.splitAndBindPassage(joinedDraft,joinedDraft.passages[1].id,at,1,'BİLE','CAYABİLİRİM.'));
assert.throws(()=>lib.splitAndBindPassage(joinedDraft,joinedDraft.passages[1].id,114.86,0,'BİLE','CAYABİLİRİM.'));
assert.throws(()=>lib.splitAndBindPassage(joinedDraft,joinedDraft.passages[1].id,114.86,1,'','CAYABİLİRİM.'));
const occupied={...joinedDraft,passages:[...joinedDraft.passages,{...joinedDraft.passages[0],id:joinedDraft.passages[1].id+':split:0'}]};
const safeSplit=lib.splitAndBindPassage(occupied,joinedDraft.passages[1].id,114.86,1,'BİLE','CAYABİLİRİM.');
assert.equal(new Set(safeSplit.passages.map(p=>p.id)).size,safeSplit.passages.length);
console.log('PASS: joined word splits into two bound words at the chosen time; neighbors, review flags and undo snapshot remain intact');
const recognizedClip={id:'recognized:0:52.959514:53.859514',start:52.959514,end:53.859514,label:'SÖZ',needs_review:true};
const duplicatePool=[recognizedClip,{...recognizedClip,needs_review:false}];
const poolSnapshot=JSON.stringify(duplicatePool);
const uniquePool=lib.uniquePassages(JSON.parse(JSON.stringify(duplicatePool)));
assert.equal(uniquePool.length,1);assert.equal(uniquePool[0].id,recognizedClip.id);
assert.equal(uniquePool[0].needs_review,true);
assert.equal(lib.uniquePassages([...uniquePool,recognizedClip]).length,1);
const collision=lib.uniquePassages([...duplicatePool,{...recognizedClip,start:54,end:55}]);
assert.equal(collision.length,2);assert.equal(new Set(collision.map(p=>p.id)).size,2);
assert.equal(collision[1].start,54);
assert.equal(JSON.stringify(lib.uniquePassages(collision)),JSON.stringify(collision));
assert.equal(JSON.stringify(duplicatePool),poolSnapshot);
const linked=lib.bindPassage({segment:{start:52,end:55,text:'SÖZ',words:[{word:'SÖZ',start:52,end:52}]},passages:collision},collision[1].id,0);
assert.equal(linked.segment.words[0].start,54);
console.log('PASS: repeated recognition and stored duplicates have unique stable IDs; distinct intervals remain selectable and warnings survive');
const uncertain={start:1,end:2,text:'MERHABA',words:[{word:'MERHABA',start:1,end:2,timing_source:'ctc',needs_review:true}]};
const uncertainSnapshot=JSON.stringify(uncertain);
const uncertainPool=lib.passagePool(uncertain);
assert.equal(uncertainPool[0].needs_review,true);
const rebound=lib.bindAllRows([uncertain],[[]]).segments[0];
assert.equal(rebound.words[0].needs_review,true);
assert.equal(rebound.words[0].timing_source,'ctc');
assert.ok(timing.timingIssues([rebound]).length);
assert.equal(JSON.stringify(uncertain),uncertainSnapshot);
const restoredPool=JSON.parse(JSON.stringify(uncertainPool));
const uncertainDraft={segment:uncertain,passages:restoredPool};
assert.equal(lib.bindPassage(uncertainDraft,restoredPool[0].id,0).segment.words[0].needs_review,true);
const uncertainSplit=lib.splitPassage(uncertainDraft,restoredPool[0].id,1.5);
const uncertainMerged=lib.mergePassages(uncertainSplit,uncertainSplit.passages[0].id);
const uncertainRebound=lib.bindAllPassages(uncertainMerged).segment.words[0];
assert.equal(uncertainRebound.needs_review,true);
assert.equal(uncertainRebound.timing_source,'ctc');
const estimated={...uncertain,words:[{...uncertain.words[0],timing_source:'estimated',needs_review:false}]};
assert.equal(lib.bindAllRows([estimated],[[]]).segments[0].words[0].timing_source,'estimated');
const verified={...uncertain,words:[{...uncertain.words[0],timing_source:'manual',needs_review:false}]};
assert.equal(lib.bindAllRows([verified],[[]]).segments[0].words[0].needs_review,false);
console.log('PASS: bulk binding and split/merge retain review flags and timing sources without changing originals');
const original={start:1,end:5,text:'MERHABA DÜNYA',words:[{word:'MERHABA',start:1,end:2},{word:'DÜNYA',start:4,end:5}]};
const draft={segment:original,passages:lib.passagePool(original)};
const edited=lib.editPassageText(draft,'merhaba güzel dünya');
assert.equal(edited.segment.words[2].start,4);
assert.equal(edited.segment.words[1].start,edited.segment.words[1].end);
assert.equal(edited.passages,draft.passages);
const withClip={...edited,passages:[...edited.passages,{id:'gap',start:2.5,end:3,label:'GÜZEL'}]};
const bound=lib.bindPassage(withClip,'gap',1);
assert.equal(bound.segment.words[1].start,2.5);assert.equal(bound.segment.words[2].start,4);
assert.throws(()=>lib.bindPassage(withClip,withClip.passages[1].id,0),/sırasını/);
assert.throws(()=>lib.bindPassage(withClip,'external',1));
const split=lib.splitPassage(draft,draft.passages[0].id,1.4);
assert.equal(split.passages[0].end,1.4);assert.equal(split.passages[1].start,1.4);
assert.equal(split.segment,original);
const merged=lib.mergePassages(split,split.passages[0].id);
assert.ok(merged.passages.some(p=>p.start===1&&p.end===2));
assert.throws(()=>lib.mergePassages(draft,draft.passages[0].id),/boşluklar/);
assert.throws(()=>lib.splitPassage(draft,draft.passages[0].id,2));
assert.equal(original.words.length,2);
console.log('PASS: insert/bind without shifting, invalid order rejected, split/merge, silence preserved, original untouched');
const corrected=lib.correctedCandidateWords('sevgili dünya yeni',original.words);
assert.equal(corrected[0].word,'SEVGİLİ');assert.equal(corrected[0].start,1);assert.equal(corrected[0].end,2);
assert.equal(corrected[1].start,4);assert.equal(corrected[1].end,5);
assert.equal(corrected[2].start,corrected[2].end);assert.equal(corrected[2].needs_review,true);
assert.equal(original.words[0].word,'MERHABA');
console.log('PASS: free text correction retains ordered audio times and gaps; extra words remain unaligned');
const bulk=lib.bindAllPassages({segment:{...original,text:'DOĞRU SÖZ'},passages:[...draft.passages].reverse()});
assert.equal(bulk.segment.text,'DOĞRU SÖZ');assert.equal(bulk.segment.words[0].word,'DOĞRU');assert.equal(bulk.segment.words[0].start,1);assert.equal(bulk.segment.words[1].start,4);
assert.throws(()=>lib.bindAllPassages({...draft,passages:draft.passages.slice(0,1)}));
assert.throws(()=>lib.bindAllPassages({...draft,passages:[{id:'1',start:1,end:4,label:'x'},{id:'2',start:3,end:5,label:'y'}]}));
assert.equal(original.text,'MERHABA DÜNYA');console.log('PASS: bulk bind preserves current text, sorts audio, keeps gaps, rejects ambiguous matches');
const rows=[{...original,text:'DOĞRU SÖZ'},{start:7,end:8,text:'EKSİK SES',words:[]}];
const all=lib.bindAllRows(rows,[[],[]]);assert.equal(all.count,1);assert.equal(all.problems.length,1);assert.equal(all.segments[0].text,'DOĞRU SÖZ');assert.equal(all.segments[0].words[0].word,'DOĞRU');assert.equal(all.segments[1],rows[1]);assert.equal(rows[0].words[0].word,'MERHABA');
console.log('PASS: project bulk binding covers all rows, preserves text, and reports untouched incomplete rows');
const detected=lib.bindDetectedSyllables({start:10,end:14,text:'DOĞRU SÖZ'},[{id:'auto:0:0:10:11',start:10,end:11},{id:'auto:0:1:11:12',start:11,end:12},{id:'auto:1:0:13:14',start:13,end:14}]);
assert.equal(detected.text,'DOĞRU SÖZ');assert.equal(detected.start,10);assert.equal(detected.end,14);assert.equal(detected.words[0].end,12);assert.equal(detected.words[1].start,13);
assert.throws(()=>lib.bindDetectedSyllables(original,[]));console.log('PASS: detected syllables bind to original words and preserve row bounds and gaps');
const partial=lib.bindDetectedWords({start:1,end:5,text:'DOĞRU EKSİK SÖZ'},[{index:0,start:1,end:2},{index:2,start:4,end:5}]);
assert.equal(partial.words[0].end,2);assert.equal(partial.words[1].end,partial.words[1].start);assert.equal(partial.words[2].start,4);assert.equal(partial.text,'DOĞRU EKSİK SÖZ');console.log('PASS: one missing word does not discard other aligned words');
const accentPartial=lib.bindDetectedWords({start:153,end:159,text:'"SÜR" DEMEDİN, YÂR'},[{index:1,start:154.5,end:156}]);assert.equal(accentPartial.words[1].start,154.5);assert.equal(accentPartial.words[2].word,'YÂR');assert.equal(accentPartial.words[2].start,accentPartial.words[2].end);
