const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ts=require('../frontend/node_modules/typescript');
function load(path,require=()=>({})){const c={exports:{},require};vm.createContext(c);vm.runInContext(ts.transpile(fs.readFileSync(path,'utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}),c);return c.exports;}
const timing=load('frontend/src/lib/karaoke-timing.ts');
const {revisePassage,addApprovedPassage}=load('frontend/src/lib/audio-passages.ts',()=>timing);
const words=[{word:'İLK',start:1,end:2},{word:'ESKİ',start:3,end:4},{word:'SON',start:5,end:6}];
const draft={segment:{text:'İLK ESKİ SON',start:1,end:6,words},passages:[{id:'selected',label:'ESKİ',start:3,end:4},{id:'other',label:'SON',start:5,end:6}]};
const original=JSON.stringify(draft);
const changed=revisePassage(draft,'selected',2.5,4.5,10);
assert.equal(changed.segment.text,draft.segment.text);
assert.equal(changed.segment.words[1].start,2.5);
assert.equal(JSON.stringify(changed.segment.words[0]),JSON.stringify(words[0]));
assert.equal(JSON.stringify(changed.segment.words[2]),JSON.stringify(words[2]));
const approved=revisePassage(changed,'selected',2.5,4.5,10,'görünmez');
assert.equal(approved.segment.text,'İLK GÖRÜNMEZ SON');
assert.equal(approved.passages[0].label,'GÖRÜNMEZ');
assert.equal(approved.segment.words[1].start,2.5);
assert.equal(approved.segment.words[1].end,4.5);
assert.equal(JSON.stringify(draft),original,'source and undo snapshot unchanged');
assert.equal(JSON.stringify(approved.passages[1]),JSON.stringify(draft.passages[1]));
for(const [a,b] of [[1.5,4],[3,5.5],[4,3],[3,11],[NaN,4]])assert.throws(()=>revisePassage(draft,'selected',a,b,10));
assert.throws(()=>revisePassage(draft,'selected',3,4,10,''));
const unbound={...draft,passages:[{id:'loose',label:'HECE',start:7,end:8}]};
const loose=revisePassage(unbound,'loose',7,8.5,10,'YENİ');
assert.equal(loose.segment,draft.segment,'unbound clip does not rewrite row');
const multi=revisePassage(draft,'selected',3,4,10,'BİR SÖZ',[{word:'BİR',start:3,end:3.3},{word:'SÖZ',start:3.4,end:4}]);
assert.equal(multi.segment.text,'İLK BİR SÖZ SON');
assert.equal(multi.segment.words.at(-1).start,5);
assert.throws(()=>revisePassage(draft,'selected',3,4,10,'BİR SÖZ',[{word:'BİR',start:2,end:3.3}]));
// Exercise the actual approval updater: stale results cannot change a draft.
const source=fs.readFileSync('frontend/src/components/AudioPassageEditor.tsx','utf8');
const tree=ts.createSourceFile('editor.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
let updater;
function visit(n){if(ts.isArrowFunction(n)&&n.body.getText(tree).includes('if(candidateClip){')&&n.parameters.length===1&&n.parameters[0].name.getText(tree)==='d')updater=n.getText(tree);ts.forEachChild(n,visit);}visit(tree);
assert.ok(updater);
const ctx={candidateRevision:{current:2},revision:{current:2},candidateClip:{id:'selected',start:3,end:4},selected:'selected',rangeStart:3,rangeEnd:4,duration:10,c:{text:'YENİ',words:[]},addApprovedPassage,
 crypto:{randomUUID:()=> 'approved'},setSelected:()=>{},setCandidates:()=>{},setNotice:()=>{},requestAnimationFrame:fn=>fn(),passagesView:{current:null}};
vm.createContext(ctx);vm.runInContext(ts.transpile('globalThis.approve='+updater,{target:ts.ScriptTarget.ES2022}),ctx);
const result=ctx.approve(draft);
assert.equal(result.segment,draft.segment,'approval never rewrites lyrics or links');
assert.equal(result.passages.length,3);
assert.equal(result.passages.at(-1).label,'YENİ');
assert.equal(result.passages.at(-1).needs_review,false);
assert.equal(JSON.stringify(result.passages.slice(0,2)),JSON.stringify(draft.passages));
const duplicate=addApprovedPassage(result,'new-id',3,4,10,'YENİ');
assert.equal(duplicate.passages.length,3,'repeated approval does not duplicate a card');
assert.equal(duplicate.passages.at(-1).id,'approved');
const existing=addApprovedPassage(draft,'new-id',3,4,10,'ESKİ');
assert.equal(existing.passages.length,2);assert.equal(existing.passages.at(-1).id,'selected');
assert.equal(existing.passages.at(-1).needs_review,false);
assert.throws(()=>addApprovedPassage(draft,'new',3,11,10,'YENİ'));
assert.throws(()=>addApprovedPassage(draft,'new',3,4,10,' '));
ctx.rangeEnd=4.1;assert.throws(()=>ctx.approve(draft),/yeniden/);
ctx.rangeEnd=4;ctx.selected='other';assert.throws(()=>ctx.approve(draft),/yeniden/);
ctx.selected='selected';ctx.revision.current=3;assert.throws(()=>ctx.approve(draft),/düzenleme/);
console.log('PASS: duration edits, scoped approval, neighbours, invalid ranges, multiple words, immutable undo, stale request protection');
